language: python

matrix:
  include:
    - name: linux-py27
      python: 2.7
      sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - CIBW_BUILD=cp27-*
    - name: linux-py34
      python: 3.4
      sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - CIBW_BUILD=cp34-*
    - name: linux-py35
      python: 3.5
      sudo: required
      services:
        - docker
      env:
        - PIP=pip3
        - CIBW_BUILD=cp35-*
    - name: linux-py36
      python: 3.6
      sudo: required
      services:
        - docker
      env:
        - PIP=pip3
        - CIBW_BUILD=cp36-*
    - name: linux-py37
      python: 3.7
      dist: xenial
      sudo: required
      services:
        - docker
      env:
        - PIP=pip3
        - CIBW_BUILD=cp37-*
    - name: osx-py27
      os: osx
      language: generic
      env:
        - PIP=pip2
        - CIBW_BUILD=cp27-*
        - CIBW_TEST_COMMAND="pytest {project}/tests"
        - CIBW_BEFORE_BUILD="${PIP} install -U pip; ${PIP} install .; $PIP install .[tests]"
      install:
        - ${PIP} install cibuildwheel==0.10.0
      script:
        - cibuildwheel --output-dir dist
    - name: osx-py34
      os: osx
      language: generic
      env:
        - PIP=pip2
        - CIBW_BUILD=cp34-*
        - CIBW_TEST_COMMAND="pytest {project}/tests"
        - CIBW_BEFORE_BUILD="${PIP} install -U pip; ${PIP} install .; $PIP install .[tests]"
      install:
        - ${PIP} install cibuildwheel==0.10.0
      script:
        - cibuildwheel --output-dir dist
    - name: osx-py35
      os: osx
      language: generic
      env:
        - PIP=pip2
        - CIBW_BUILD=cp35-*
        - CIBW_TEST_COMMAND="pytest {project}/tests"
        - CIBW_BEFORE_BUILD="${PIP} install -U pip; ${PIP} install .; $PIP install .[tests]"
      install:
        - ${PIP} install cibuildwheel==0.10.0
      script:
        - cibuildwheel --output-dir dist
    - name: osx-py36
      os: osx
      language: generic
      env:
        - PIP=pip2
        - CIBW_BUILD=cp36-*
        - CIBW_TEST_COMMAND="pytest {project}/tests"
        - CIBW_BEFORE_BUILD="${PIP} install -U pip; ${PIP} install .; $PIP install .[tests]"
      install:
        - ${PIP} install cibuildwheel==0.10.0
      script:
        - cibuildwheel --output-dir dist
    - name: osx-py37
      os: osx
      language: generic
      env:
        - PIP=pip2
        - CIBW_BUILD=cp37-*
        - CIBW_TEST_COMMAND="pytest {project}/tests"
        - CIBW_BEFORE_BUILD="${PIP} install -U pip; ${PIP} install .; $PIP install .[tests]"
      install:
        - ${PIP} install cibuildwheel==0.10.0
      script:
        - cibuildwheel --output-dir dist
install:
  - ${PIP} install -U pip
  - ${PIP} install tox
  - ${PIP} install -r docs/requirements.txt
  - ${PIP} install cibuildwheel==0.10.0
script:
  - ${PIP} install .[flake8]
  - flake8 --ignore=E501 lz4
  - flake8 --ignore=E501 tests
  - flake8 --ignore=E501 setup.py
  - ${PIP} install .
  - ${PIP} install .[tests]
  - pytest
  - make -C docs doctest html
  - cibuildwheel --output-dir dist
deploy:
  - provider: pypi
    # server: https://test.pypi.org/legacy/
    user: jgu
    password:
      secure: SS5kSQtsfHIYG5gLKC9jQ23bnNBgoejVgdrDxfaccNqojrIy5CtuUo+a7/P16bObWp1jCnlwUyX6mQj1S+abDsUHr+2+pNjl5MP8pWdREu19fBTcwMkZLXlUdSuWwcBjmZjaVpuKQRCKwajHrGjOE4s3vO1h/IOLETEX0d1rmuavSUftqYcea/TO/MNzDuxnUe7pkGsPkfbMxHY5oXNmx5zOvtG2h0eZowjwgE5YVZfTZ82fqfCfbqmoytwmQKd3rTmo/hpYvNcGweHizKouzLArw0+DDtkJt/jT459zM3lnUEh+TfaCSeqd+cTWmEZDiMR8MxnSJkpN3RGHcvxreF+HZjCAKhvAbZcWIpRC0cNp4VxWyVGZN/dLZA0WM3gJJKCjgCA70eslC+ccZh6WyG93effiVLhHYB9vyt7SfwsUzDrZo3++Czi6drCVNyI6pBdb587yfkuJYdomNIQ2DCesUKjuoFFt34VZC5bJOK82F81jMXYGaQn3BCWPdfMTmqJ3maimfji7KXts6bbyQUzgc+610Yd8eIRGvDQwmeBjovRT5uyYDJtXfDOIYXiv3n79wtDt+ygZzLOXNMvEt6/Wsy/xrWEsHFfA5bknSenurfgQoYCkLOjgKJEqxDV4nXdwhJxwbC740Fea/cGwem5L0mfz8SGtd7giFHDpgkg=
    distributions: "sdist"
    on:
      branch: master
      tags: true

