version: '{build}'
image: Visual Studio 2022

environment:
  matrix:
    - PYTHON_VERSION: "3.13"
    - PYTHON_VERSION: "3.10"
    - PYTHON_VERSION: "3.9"

install:
  - cmd: powershell -Command "Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.13.1/python-3.13.1-amd64.exe -OutFile python-installer.exe"
  - cmd: start /wait python-installer.exe /quiet InstallAllUsers=1 PrependPath=1
  - cmd: refreshenv
  - cmd: python --version
  - cmd: pip install --upgrade pip setuptools wheel

build_script:
  - cmd: python setup.py bdist_wheel

artifacts:
  - path: dist\*.whl
    name: python-lz4-wheels
